### ISSUE TITLE
Remove v2 branch?

### ISSUE THREAD

**Issue by TimothyGu** [mde/ejs#10]
ejs v2 has already been published to npm, and the v2 branch has already been fully merged into master. Therefore I think it should be removed now.

**Comment by mde** [comment]
All my projects follow a "release branch" strategy, rather than a "release from master" strategy. Development happens in master, and only bug fixes get committed to the release branch (currently v2). These are then constantly merged back to master. This is how I'm used to doing things, but I'm not religiously tied to it. If people prefer doing things a different way, it's fine as long as it's clear where development happens, and we have a stable branch that always represents whatever should be used in production.

It's also worth noting we have two built files for browsers that should usually go in a release. v1 had these committed into revision control, which is not optimal for things which are created as part of a build. Currently I'm manually creating a GH Release when something significant changes, and manually building (`jake build`) and uploading those files. I was hoping to add some hooks into the current `jake publish` flow which would automate that process as well.

**Comment by TimothyGu** [comment]
@mde said:

> All my projects follow a "release branch" strategy, rather than a "release from master" strategy. Development happens in master, and only bug fixes get committed to the release branch (currently v2).

This is completely fine for me, but I was just confused about the branching scheme as master and v2 are basically the same thing, and we do not intend to break backwards compat in master in the near future.

What we are doing in Jade is basically everything happens in master, and once design flaws and old bugs (whose fixes would break backward compat) pile up, we branch out to a new branch, and concurrent development happens with v2 routinely merged from master. When v2 is mature enough (and when we have too many fixes piled up) we merge from it.

Considering the fact that we are not like the Linux kernel or huge projects with multiple supported release branches, I feel that the Jade system works pretty well; but if you prefer to *always* have a production branch, go ahead, I don't hold a strong opinion.

**Comment by mde** [comment]
I generally like having a prod branch just to make it clear what's stable. As you pointed out, this shouldn't be under heavy development, so it might be superfluous. Let's keep things as they are for now, and if it gets too confusing we can revisit. I'll close this issue for now.

**Comment by TimothyGu** [comment]
OK, no problem for me.

**Comment by mde** [comment]
:+1:

**Comment by mde** [comment]
Okay, I've removed the release branch, and pushed up a development branch. We'll use a release-from-master strategy, where the latest tag should be what's in production. The development branch is for non-bugfix work -- new features, non-backward-compatible changes, etc.

**Comment by TimothyGu** [comment]
Cool :)
