### ISSUE TITLE
Streaming Support

### ISSUE THREAD

**Issue by jpodwys** [mde/ejs#102]
I'd love to have streaming support so I can progressively stream the rendering EJS to the client a la [then-jade](https://github.com/jadejs/then-jade#renderstreamingstr-options).

**Comment by mde** [comment]
This is possible -- Geddy's use of EJS (https://github.com/geddy/geddy) works this way for partials. But it does add significant code complexity, and doesn't really stream the rendering of individual templates (since each template is a JS program that runs) -- it streams the loading of nested/included templates. And if template text is generally cached, it's dubious how much value async loading brings compared to the increased complexity. I'd be happy to look at a PR that implements this though, if it could do it relatively simply.

**Comment by jpodwys** [comment]
Would you be able to point me in the right direction? I've spent 2-3 hours looking at the EJS source and I'm not sure where to start. Thanks!

**Comment by jpodwys** [comment]
For the time being, I've written a view engine-agnostic response streaming middleware for Express called [express-stream](https://github.com/jpodwys/express-stream) to meet my needs. It works great, but isn't quite the drop-in solution I was hoping for, although it does provide a very high level of flexibility. If I could add streaming into EJS is such a way that it immediately appended each line that finishes compiling and rendering to an out-bound buffer, then that might make it so express-stream was no longer necessary, at least for projects using EJS.

**Comment by acrazing** [comment]
Hey gays, may be you can try [acrazing/ejs-stream](https://github.com/acrazing/ejs-stream). I write it for mix `ejs` and `React`s `renderToNodeStream` API.

Hope it helps you.
