### ISSUE TITLE
How to work with DOM.

### ISSUE THREAD

**Issue by EasonWang01** [mde/ejs#134]
Is it possible to using something like this?
```
<% var bt = document.getElementById("page2");
        bt.addEventListener('click',function(){
          alert("123")}); %>
```
thanks for reply.

**Comment by RyanZim** [comment]
What's wrong with this?
```
<script>
var bt = document.getElementById("page2");
        bt.addEventListener('click',function(){
          alert("123")});
</script>
```

Are you using ejs on the client-side?

**Comment by EasonWang01** [comment]
It's on the client side

not found repo about this http://www.embeddedjs.com

So post issue here,I know it's different one.

**Comment by RyanZim** [comment]
I'm still not getting why you would use DOM manipulation in EJS instead of using the `<script>` tag.
Perhaps you could provide an example of what you're trying to do?

**Comment by EasonWang01** [comment]
For example
```
<button  id="btn" onclick="function a()" />

<script>
var as = true ;
var bt = document.getElementById("btn");
        bt.addEventListener('click',function(){ 
if(as){
<li><%=  This is true %><li>
var as =false ;
}else{
<li><%=  This is false %><li>
}

};

</script>     
``

**Comment by RyanZim** [comment]
This isn't how EJS works. To use it on the client side, you would do something like:
```
var name="John Doe";
var str="Hello <%= name %>!";
var result=ejs.render(str);
document.write(result);
// => Hello John Doe!
```
Of course you would use something other than `document.write`.

Includes are not natively supported on the client side.

Warning: Doing complex EJS logic on the client side can get very messy since JS support for multi-line strings isn't very good. (This doesn't apply if you are getting your EJS templates from an external file via AJAX.)

**Comment by RyanZim** [comment]
@EasonWang01: If you have more questions, feel free to post them here; otherwise I will close this issue in a few days.

**Comment by EasonWang01** [comment]
ok,I found that I can using html = new EJS({url: '/template.ejs'}).render(data)

on client side
