### ISSUE TITLE
how to use ejs.js as amd or cmd mode under the browser env.

### ISSUE THREAD

**Issue by honwsn** [mde/ejs#146]
how to use ejs.js as amd or cmd mode under the browser env.

**Comment by RyanZim** [comment]
We currently do not support AMD since this is a node (CommonJS) module that we have made available for use on the client side with [Browserify](http://browserify.org/). I'm not sure if AMD support is something @mde would be interested in doing or not.

I'm not sure what you're referring to as "cmd mode".

At the present time, if you don't like having the `ejs` object available globally, there are a number of options:

1. If you're using RequireJS or Webpack as your AMD module loader, they both support loading CJS Modules. (No personal experience with either one.)
2. You could `require` EJS in in your code and than build your code using [Browserify](http://browserify.org/).
3. You might be able to wrap the source code (lib/ejs.js) yourself with something like:
```
define(function(require, exports, module) {
    // ejs source code here
});
```
I haven't tried it personally.

**Comment by mde** [comment]
I had a look at making EJS an UMD module using something like this: https://github.com/umdjs/umd But I haven't gotten around to implementing it.

**Comment by RyanZim** [comment]
@mde if this were implemented, would the UMD files replace the current Browserified files?

**Comment by honwsn** [comment]
thanks all， my project is using requirejs , i just want wrap ejs code and pack it by requirejs .
just as follows that @RyanZim mentioned it above
`define(function(require, exports, module) {
    // ejs source code here
});`

**Comment by zen-mde** [comment]
@RyanZim Yes, the UMD file would replace the Browserified one -- in theory it should be compatible (hence the 'universal'), but we'll want to check.

**Comment by honwsn** [comment]
`define(function(require, exports, module)
 { // ejs source code here });`

I try it ，cannot work。

it cannot run in amd or cmd mode under the browser env .

i had to give up it.  reading the ejs code  is not well, especially in parameters transfer.

**Comment by honwsn** [comment]
@mad @RyanZim  backbone did support amd ,CommonJS,and brower env  by add only a few lines code
like [follows:](http://backbonejs.org/backbone.js)
`(function(factory) {

  // Establish the root object, `window` (`self`) in the browser, or `global` on the server.
  // We use `self` instead of `window` for `WebWorker` support.
  var root = (typeof self == 'object' && self.self === self && self) ||
            (typeof global == 'object' && global.global === global && global);

  // Set up Backbone appropriately for the environment. Start with AMD.
  if (typeof define === 'function' && define.amd) {
    define(['underscore', 'jquery', 'exports'], function(_, $, exports) {
      // Export global even in AMD case in case this script is loaded with
      // others that may still expect a global Backbone.
      root.Backbone = factory(root, exports, _, $);
    });

  // Next for Node.js or CommonJS. jQuery may not be needed as a module.
  } else if (typeof exports !== 'undefined') {
    var _ = require('underscore'), $;
    try { $ = require('jquery'); } catch (e) {}
    factory(root, exports, _, $);

  // Finally, as a browser global.
  } else {
    root.Backbone = factory(root, {}, root._, (root.jQuery || root.Zepto || root.ender || root.$));
  }

})`

**Comment by RyanZim** [comment]
@honwsn I tried wrapping EJS in `define` myself and it won't work. The reason is that since EJS is written in CommonJS, it contains CommonJS `require()` statements; which AMD loaders try to parse as AMD `require`s. Of course, they can't parse them as such.

I want to try https://github.com/anodynos/uRequire to port EJS to UMD; not sure when I'll get to it.

**Comment by RyanZim** [comment]
@honwsn, @mde, @zen-mde, and all others interested:

I managed to get a UMD version of EJS made using uRequire. It's not simple.

I installed urequire and created an output directory `umd/` in the project root. I then ran `urequire UMD lib -o umd`. This compiles the files in `lib/` and puts them in `umd/`.

In order to get RequireJS to load EJS, I had to **manually remove** the following snippets from the resulting ejs.js:

- `_VERSION_STRING = require("../package.json").version, `
- ` '../package.json'`
- ` fs = require("fs"),`
- `exports.VERSION = _VERSION_STRING;`

Then I was able to use EJS as an AMD module. I haven't fully tested it, but it should work the same as the browserifyed files with the exeption of `ejs.version` not being available. (You could manually change `_VERSION_STRING` to the current version manually if you needed it.) I didn't try using them in any way other than via AMD (RequireJS).

I attached the (unminifyed) UMD files for the benefit of anyone who wants to use them. 
[ejs-umd.zip](https://github.com/mde/ejs/files/206655/ejs-umd.zip)
They are built from commit 958c80d9c5b286ed2f88b81329b3eb8956cb6618. You would need to put ejs.js and utils.js on the same directory level.

I am not interested in generating UMD files for future releases; and it will take someone smarter than me to figure out how to automate this process in a robust way. Funny that I did this much considering that I hate AMD!

**Comment by honwsn** [comment]
@RyanZim  yeah, i had modified it last night,  it did work under commonJs mode.   i have one question about include tag: it has two patterns:

1.  <% include circleTop.ejs %> for express' ejs
2. <% include('circleTop')%>  for you lib

how to compatible ，this two patterns.

**Comment by honwsn** [comment]
i got it 
<% include circleTop.ejs %> for express's ejs
<%- include('circleTop')%> for ejs lib

**Comment by RyanZim** [comment]
@honwsn: You are incorrect about includes. Please read about them here: https://github.com/mde/ejs/blob/master/docs/syntax.md#including-other-files

**Comment by honwsn** [comment]
@RyanZim   I write ejs for express ,use following patterns:
`<% include **.ejs %>`

write ejs for mde version, use  `<%- include('**.esj') %>`
this pattern is also support by express's render

**Comment by RyanZim** [comment]
I am closing this issue since it doesn't seem like UMD/AMD support is something we'll be adding in the near future.

If someone can figure out a robust way to render this lib to UMD as part of the build process, they are welcome to open a new issue describing their method. If their method is good, I would welcome a PR implementing it.
