### ISSUE TITLE
ejs used in browser env.  the "include" tag <%include %> did not effect

### ISSUE THREAD

**Issue by honwsn** [mde/ejs#147]
ejs used in browser env.  the "include" tag <%include %> did not effect. has exception as follows:

"fs.readFileSync is not a function"

i just want remove this exception, if my ejs file has include tag.

**Comment by zen-mde** [comment]
The `include` directive/method is only usable on the server. It has to read a file off the filesystem to include. The browser doesn't have filesystem access to read files, nor would it be performant/desirable to pull include files down over XHR or some other method.

What do you mean by "remove this exception"? Seems a bit hacky to want to ignore exceptions that occur because you're using the lib in an obviously unsupported way.

**Comment by honwsn** [comment]
I means if ejs run  in browser,  if ejs file has include tag , it should be    ignored.

**Comment by RyanZim** [comment]
I'm not sure if the `IncludeCallback` would help; It's not well documented & I haven't got it running myself; see #144.

**Comment by honwsn** [comment]
@RyanZim  i try it last night, modify `include callback` as empty function, would did it.

**Comment by RyanZim** [comment]
Glad you got it! Closing.
