### ISSUE TITLE
Documentation: Utility Functions

### ISSUE THREAD

**Issue by breandr** [mde/ejs#182]
What's the best way to add utility functions? For example, converting strings to camel, title, dashed, underscored, etc. Is the preferred way to just pass in functions in the options which then get exposed to the template? This seems common enough to warrant being built into core ejs. Thoughts?

**Comment by RyanZim** [comment]
As outlined in https://github.com/mde/ejs#usage, we don't recommend passing options and data together; it's better to pass them separately, like this:
```
ejs.render(str, data, options);
```

Regarding passing utility functions, you can pass them as part of the data.

If you are worried about name collisions with your data variables, you could also pass them in `options.context`. This would allow you to access them under `this` like: `<%- this.toCamel(str) %>`. You might want to check the performance impact this has; I'm not sure.

> This seems common enough to warrant being built into core ejs.

We generally try to keep EJS small and free from bloat; I'm not in favor of this & I doubt the other collaborators would feel otherwise. The other problem is that users expect nothing to be defined inside their templates except `include()` and their `data`. Adding string utils would break that expectation.

You might want to look at passing a module like https://www.npmjs.com/package/ustring as part of the `data`, like this:
```
var data={};
data.ustring=require('ustring');
ejs.render(str, data, options);
```

**Comment by breandr** [comment]
Thanks!
