### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by loganto** [mde/ejs#190]
It  would be nice to have an AMD support so it could be easily usable in the browser.

```
(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD
        define(['jquery'], factory);
    } else if (typeof exports === 'object') {
        // Node, CommonJS-like
        module.exports = factory(require('jquery'));
    } else {
        // Browser globals (root is window)
        root.returnExports = factory(root.jQuery);
    }
}(this, function ($) {
    //    methods
    function myFunc(){};

    //    exposed public method
    return myFunc;
}));
```

**Comment by RyanZim** [comment]
It's something we've thought of, but since EJS is written in CommonJS, it's not quite that simple.

> The reason is that since EJS is written in CommonJS, it contains CommonJS `require()` statements; which AMD loaders try to parse as AMD `require`s. Of course, they can't parse them as such.

You can read about my attempt here: https://github.com/mde/ejs/issues/146#issuecomment-206418722.

As I said there:

> If someone can figure out a robust way to render this lib to UMD as part of the build process, they are welcome to open a new issue describing their method. If their method is good, I would welcome a PR implementing it.

I personally don't have time to fool with it. (I don't use EJS in the browser anyhow)

**Comment by TimothyGu** [comment]
I recently came across [rollup.js](http://rollupjs.org) that allows you to write your code in ES2015 module syntax (i.e. `import` & `export` statements), and output ES3 code in AMD, CommonJS, Globals, and UMD. Might be useful if we want to migrate to ES2015.

**Comment by RyanZim** [comment]
I was working on my personal site today, and I had to look at the browserify CLI docs for something. Reading over the CLI options, the `--standalone` option jumped out at me. I didn't even know it existed.

From https://github.com/substack/node-browserify#usage:

>  ```
 --standalone -s  Generate a UMD bundle for the supplied export name.
                  This bundle works with other module systems and sets the name
                  given as a window global if no module system is found.
```

I gave it a try this evening, and was able to automatically export EJS as a UMD module! I tried loading it with RequireJS and using as a browser global. Both tests were successful. :tada:

**Comment by RyanZim** [comment]
Looking at the Jakefile to automate this:
```
task('browserify', {async: true}, function () {
  jake.exec('./node_modules/browserify/bin/cmd.js lib/ejs.js > ejs.js',
      buildOpts, function () {
    console.log('Browserification completed.');
    setTimeout(complete, 0);
  });
});
```
`'./node_modules/browserify/bin/cmd.js lib/ejs.js > ejs.js'` is quite the long-winded command! I don't want to start bikeshedding, but this is just a prime example of the benefits of npm scripts.

The current Jakefile is 47 lines. The exact equivalent could be accomplished in just 7 lines using npm scripts:
```
"scripts": {
  "build": "npm run browserify && npm run minify && echo \"Build completed.\"",
  "browserify": "browserify lib/ejs.js -s ejs -o ejs.js && echo \"Browserification completed.\"",
  "minify": "uglifyjs ejs.js > ejs.min.js && echo \"Minification completed.\"",
  "clean": "rimraf ejs.js ejs.min.js",
  "prepublish": "npm run build"
}
```
To be fair, we'd have to add ~5 lines for the npm `files` array (instead of [Jakefile#L34-43](https://github.com/mde/ejs/blob/master/Jakefile#L34-43)), but 12 vs. 47 lines is still quite a big difference.

**Comment by TimothyGu** [comment]
FWIW, the command can be simplified a bit if you add the `.bin` directory to `process.env.PATH`, so that the syntax looks more or less the same as npm scripts. I do like the flexibility of writing stuff in JavaScript instead of "shell" (which isn't even a full UNIX shell because of Windows cmd.exe compatibility).

**Comment by RyanZim** [comment]
OK, whatever.

I'm adding the `enhancement` label. I'll try to add the -s option later today, but PR welcome as well.

@TimothyGu Should we add tests for using EJS in an AMD environment?

**Comment by RyanZim** [comment]
@loganto Until the next release, here is the UMD file of the latest `master` branch:

[ejs.min.js.txt](https://github.com/mde/ejs/files/364442/ejs.min.js.txt)

You will need to save it as a `.js` file.

**Comment by loganto** [comment]
@RyanZim wow. awesome. Thanks for taking a time!
