### ISSUE TITLE
Including partial views using absolute path.

### ISSUE THREAD

**Issue by omerman** [mde/ejs#205]
Hi, I have a project that works fine on version 2.5.1 and breaks when it uses 2.5.2
When I include a partial view using absolute path it fails on Linux system only(it did work perfectly in Windows for some reason) 

Let's say I have a project:

project-folder
-app
--f
---f1.ejs
--partials
---p1.ejs
--app.js

app.js
```
//the important piece of the express initialization content on app.js
  app.set('view engine', 'ejs');
  app.set('views', path.join(__dirname, 'app'));
```

f1.ejs content:
```
<% include /partials/p1 %> // notice the absolute path, `/partials/..`
```

I will receive an error

```
Error: ENOENT: no such file or directory, open '/partials/p1.ejs'
```

-------------------------------------------------

I've found the commit that produced this issue.
[Here it is](https://github.com/mde/ejs/commit/f7f8ab05fa8306baa78a622f1f3e0f97606139b7)
@RyanZim 

This commit has 3 lines of code that were deleted.

After re-adding these lines, my project was successfully able to find the partial views using the absolute path relative to path-to-project-folder/app
```
app.set('views', path.join(__dirname, 'app'));
```

Since I know that restoring the deleted code is obviously NOT a proper fix( it was not deleted just for fun as I viewed from the issue it is attached to)
I think it should be handled in another way.

Thanks in advance.

**Comment by RyanZim** [comment]
v2.5.1 was a buggy release. Before that release, absolute paths referred to the literal Linux filesystem root. In that release we added the `root` option, to allow for setting a path to use as root. We accidentally included the lines that auto-set `root` for express users. Those lines never should have been added, since they broke backwards compatibility. Unfortunately, you were relying on this buggy behavior.

You can create the desired `root` behavior by setting the `root` option to `path.join(__dirname, 'app/partials')`. Sorry for the inconvenience.
