### ISSUE TITLE
New-line slurping not working as expected

### ISSUE THREAD

**Issue by upman** [mde/ejs#226]
```
ejs.render('<%_ if(true) { _%>\n   Hi\n<%_ } _%>')
// Returns: '   Hi\n'
// Expected:  'Hi'
```

**Comment by RyanZim** [comment]
@mde @TimothyGu  What's the intended behavior here?

**Comment by RyanZim** [comment]
@mde @TimothyGu ping?

**Comment by mde** [comment]
Docs should say "removes all *non-linebreak* whitespace" for these tags. This tag leaves linebreaks alone, so in this example, after the linebreaks are factored in, you have `'   Hi'` on a line by itself, and no leading or trailing whitespace directly before or after a tag.

Part of the issue here is that this is a formatting function, and kind of implemented as a one-off. IMO this is really the type of thing we should be leaving to an HTML prettifier. We should consider removing this feature in v3, and leave only the minimalist `-%>` tag.

**Comment by RyanZim** [comment]
Thanks @mde, wasn't sure exactly how that was supposed to work.
