### ISSUE TITLE
Help wanted: Client side rendering of remote files

### ISSUE THREAD

**Issue by AmarPrabhu** [mde/ejs#256]
I am upgrading some templates that were rendered using the old http://www.embeddedjs.com/ library which supports client side rendering.

I am looking for a method similar to:
`new EJS({url: '/template.ejs'}).render(data)`

For the current repository, how do I use remotely hosted template files?

The examples only show how to do it with a template string like:
`ejs.render('<%= people.join(", "); %>', {people: people});`

**Comment by RyanZim** [comment]
This version of EJS is a bit more lightweight, you have to do the ajax fetching yourself. 

Some different libraries for doing ajax:
- If you're using jQuery, it includes a built-in `$.ajax` method
- `fetch` is a web standard, but you'll need a polyfill for older browsers: https://github.com/github/fetch
- https://github.com/visionmedia/superagent

**Comment by mde** [comment]
For some more context, that other EJS project has been around since before the frontend ecosystem had extensive tooling and build processes. Loading multiple small files (like templates) one at a time is not a modern best-practice. (There is also the delay in rendering while fetching the template, which could be significant on slow networks.) You should likely be concatenating/minifying your templates and pulling them down once as part of the initial page-load.

**Comment by NextZeus** [comment]
@RyanZim why not write some demo in README , client render template issues is so many .
