### ISSUE TITLE
[OFF-Topic] Simple web server with ejs support

### ISSUE THREAD

**Issue by vpontin** [mde/ejs#261]
Hi! Sorry about this useless issue, but i'm a very noob node user, i meet EJS in [this SO answer](https://stackoverflow.com/a/18147361/4836556), and i LOVE the idea  ❤️ !

But when i searched about an EJS "Getting Started" most examples uses express, from what i understand is a sighly advanced library for me.

So my question is: Is there any simple (zero-config, just point to a path and voilá) webserver like [this one](https://github.com/indexzero/http-server) but with support for EJS?

If not, is there any simple alternative for local developement (mostly about frontend, i dont want to worry much about server-side things).

Thanks in advance!

**Comment by RyanZim** [comment]
@vpontin If you want to use EJS simply to compile HTML for the frontend (the site doesn't have a dynamic backend), you're looking for something called a Static Site Generator. Here's a list (note that not nearly all of them support EJS; some aren't even written in JS): https://www.staticgen.com/ Hope that's helpful. I personally use my own static site generator https://github.com/RyanZim/onessg; but it might be a bit advanced for you.

**Comment by vpontin** [comment]
I think i wasnt clear in my elaboration (sorry, my english is so-so).

I mean i want to get a node package with a simple back and frontend for dev, without too much pain to configure, like that one i've mentioned, but with simple backend capabilities.

**Comment by mde** [comment]
Express is fairly straightforward to set up. However, for simplicity of setup and ease of use, an actual MVC framework might be what you're looking for. One example would be the Geddy framework (http://geddyjs.org/tutorial -- disclaimer, I am the author 😄 ). Geddy makes it extremely easy to set up a working app, and defaults to EJS for its templating language.

Note however that a significant majority of Node community has historically exhibited an extreme hostility to any sort of framework -- largely due to prioritizing modularity above all other concerns.
