### ISSUE TITLE
support async/await

### ISSUE THREAD

**Issue by acthtml** [mde/ejs#262]
I find the way to support 'async/await'.

```js
let tempate = 'Hello <%- await getName() %>';
let getName = () => {
  return new Promise( (res, rej) => {
     setTimeout(() => {
        res('John');
     }, 1000)
  })
}
html = await ejs.render(template, {getName});
// Hello John.
```

HOW TO ?

```js
//  lib/ejs.js  line 523
try {
      // let fn to be async.
      eval(`fn = async function(${opts.localsName}, escapeFn, include, rethrow){${src}}`);
      // fn = new Function(opts.localsName + ', escapeFn, include, rethrow', src);
}catch(e){
  // ....
  // ....
}
```

**Comment by mde** [comment]
The issue here is that `render` is a synchronous function that returns a string value. Even though `async`/`await` hides a lot of the asynchrony, it's still just wrapping around a Promise API, so all consuming code either itself has to be declared as `async` (no direct return value possible, similar to callback) or has to be Promise-aware (actual Promise object returned).

To make template-function execution work with `async`/`await`, there will need to be some significant rework (e.g., use AsyncPromise constructor for template function), and likely a separate, async-aware API created. In that case, it might be better to consider making it explicitly Promisey, so it could be easily use with `async`/`await` code.

**Comment by RyanZim** [comment]
@mde Sometime, I think we should work on a major version of EJS adding promise support, etc. Not sure when though.

**Comment by mde** [comment]
Seems like a good idea, but thinking about when async generally comes into play, there are a few general cases -- when there is I/O, or reacting to events, or streams of events. Thinking about those cases, the EJS rendering shouldn't come into play in any of them.

You generally shouldn't be doing I/O as a part of rendering a template. That should happen when you're reading the template file (that's why we cache), and marshalling the data for rendering (we expect this to happen out of band, and have it passed in). Events and streams shouldn't be happening *inside* the EJS rendering process (although I have seen some attempts at streaming template systems, the utility seems kind of dubious to me). 

In fact Geddy's template system (which could plug in EJS or other templating languages) handled the template-reading I/O in a fully async way (https://github.com/geddy/geddy/blob/v14/lib/template/partial.js). But again, the actual rendering for each templating language was assumed to be blocking execution.

**Comment by RyanZim** [comment]
@mde I was thinking more about `renderFile`. Also, I've thought it would be nice to at least allow an async `include` sometime; just a thought.

**Comment by mde** [comment]
That's basically how the Geddy template rendering process works (async and bottom-up). We might be able to take some cues from there.

**Comment by whiskas** [comment]
don't do that! keep ejs fast and simple!
If you need, you have to do asyn/await wrap around ejs render call.

**Comment by ilanl** [comment]
A template system should not be opinionated. 
If you need to a dynamic language for constructing dynamic messages, async requirement is legitimate.
Why close this?

**Comment by RyanZim** [comment]
EJS now has an `async` option.
