### ISSUE TITLE
CommonJS require within template fails under certain test envs (Jest, Mocha..)

### ISSUE THREAD

**Issue by veksen** [mde/ejs#308]
A template containing a require, like so:
```
<% const myFunc = require('./helpers').myFunc %>
<%= myFunc(whatever) %>
```

will correctly render in a Node environment, but will fail within a test.

I thought my env was poorly setup (maybe it is?!), so I reproduced my issue in your test suite, and I get the same result, see my failing test here:
https://github.com/veksen/ejs/commit/a46667ce7e3e78b19fcc9708a9890227495b7770

**Comment by RyanZim** [comment]
`require` shouldn't work within templates; I'm not sure how you ever managed to get it working in Node.

**Comment by mde** [comment]
In theory, the EJS template renders in whatever context you invoke `render` in, so globals like `require` or `console` should indeed be available. But your test env might not be loading code in the standard way, so it's possible some of these things might not be available. This is a concern of your test framework, not EJS. EJS is deliberately minimal, so it has nothing to do with whatever context it happens to be executing in. You're more likely to get help by talking to the folks who have built your test runner(s).

I'm closing this for now, since it's not something within the purview of EJS. Happy to reopen if some further discussion is warranted.

**Comment by veksen** [comment]
@mde Note that it also fails in your own test environment, see my fork in my original comment.

I'm aware that this is a specific workflow that doesn't happen to other people. I also thought it was specific to my test env, which is why I attempted to reproduce my "bug" in your env.

I assume that the workaround is to pass whatever required functions/variables to the render method, which is not something sane for me to do, as a lot of those are needed by partials.

Thanks a lot for looking at this.
