### ISSUE TITLE
Deprecation notice when rendering in Express with valid data and no options

### ISSUE THREAD

**Issue by nallenscott** [mde/ejs#34]
Rendering in Express with `res.render( 'master', { mainjs: mainjs, maincss: maincss } )` displays a deprecation notice, even when there are no 'optiony names in the data'.

**Comment by TimothyGu** [comment]
@nallenscott Express internally adds some options to the locals object.

**Comment by nallenscott** [comment]
@TimothyGu Thank you.

**Comment by dougwilson** [comment]
You cannot export a `__express` property on your module if you're going to yell at everyone. Exporting an `__express` property means you're agreeing to support the defined interface of `__express`, which is to mix locals and options.

It's like someone came by asking if you could help them as long as you did it their way (i.e. Express checks for `require('your_module').__express`) and you agreed you would (because you defined a function there), but then whenever they asked for help (called `__express()`), you yelled at them that you won't do it their way.

**Comment by TimothyGu** [comment]
@dougwilson ... which is the reason why I opened #37.

**Comment by dougwilson** [comment]
@TimothyGu sorry, I didn't read that issue as a "we'll make the deprecation message not exist when called through `__express`", my bad :)

I actually just hit this message myself in multiple places. 1. since it's just a random message, it's really hard to track down which one of my `renderFile` calls that is causing it (especially since it depends on the data going to it) and 2. there doesn't seem to be any mechanism for me to turn off the warnings until I have the time to deal with the issue :)

**Comment by nallenscott** [comment]
Wait. Why was this ticket closed? And why is there a new ticket RE the same issue? This isn't about working around some issue with Express. This is clearly not Express's fault. You advertise as being fully compliant with the Express view system. You're not. Simply concede that there is a issue with your module. If anything, I would like to see #37 closed (no description, treating it like an enhancement), and this one reopened (identifies an issue, treats it like an issue).

**Comment by mde** [comment]
Sorry this is causing problems for people. A deprecation notice is just that, a notice. It's not an actual error. I get that it pollutes your logs, and we need to fix it. We're working through a major version change here, and there are definitely some bumps. Sorry for the inconvenience. I'll try to get a fixed version pushed to NPM today.

**Comment by dougwilson** [comment]
It's not just server logs; it's when it appears in the CLI output from user programs, haha, and there isn't a way to turn it off :)

**Comment by TimothyGu** [comment]
@nallenscott whatever.

**Comment by mde** [comment]
Fixed in 3134613044c4b11852dc250ff4d52705cf54ede5 and pushed to NPM in v2.2.2.
