### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by songzhuang** [mde/ejs#359]
Hi, 
I have developed a system with node.js, express with ejs as the rendering engine.  The application locks up after about 30 minutes of run time.  Using the Chrome debugger, looks like there is a memory leak when ejs does the rendering.  eg.  If I click on a link 5 times, the html for the 5 is not garbage collected.  

How would I handle this?
Thanks,

**Comment by secreter** [comment]
mark.It's seams I met the same problem.

**Comment by mde** [comment]
EJS just creates a function out of your template string, then runs it with your data as input parameters. It's highly unlikely that this is a memleak issue in EJS itself. (EJS is also a pretty widely used module, so any memleak issues would be visible to tons of people.)

Since you're seeing this problem in the browser, it seems more likely that references to either the returned HTML, or to the created DOM node, are still hanging around, preventing that memory from getting GC'd.

If you could provide a very minimal test to demonstrate this, I might be able to help, but I'm pretty sure this is an issue with your application, not with EJS.

**Comment by lxcid** [comment]
Hmmm, I think I might have met this problem too.

**Comment by jackycute** [comment]
I used `node --inspect app.js` to run our server and use ApacheBench to test it.
Then I found that data in memory stack are mostly from the ejs rethrow related function.
Anyone have clues or this is normal?
<img width="1215" alt="2018-06-01 10 30 18" src="https://user-images.githubusercontent.com/2639151/40846166-67ef145e-65eb-11e8-864f-120b4f429e58.png">

**Comment by mde** [comment]
What I'm seeing in the screenshot looks like a string variable for the source that the EJS Template object uses to compile into a runnable function. Depending on what's in your template text, this could be very large.

**Comment by mde** [comment]
Again, given how widely used EJS is, any memleak problem in EJS itself would be immediately visible to a huge group of people. If someone can provide a minimal test demonstrating a memleak in EJS, I'm happy to take a look, but I'm going to close this issue for now since it's mostly people talking vaguely about memleak issues in their apps, and nothing specific to EJS. We can certainly reopen if there's any evidence of a real memleak issue in EJS.

**Comment by magic890** [comment]
Same problem here, with the `string` and `concatenated string`. Seems that they are not going to be collected by GC.

@songzhuang @lxcid @secreter @jackycute @mde did you find any solution or workaround?

**Comment by Starystars67** [comment]
Dear @mde i have encountered this issue too here is a copy of code that i have used to minimize the external variables, ignore the moment library its used for the ejs page i was loading from my project.
`const memwatch   = require('memwatch-next');
var moment = require('moment');

// load the things we need
var express = require('express');
var app = express();

// set the view engine to ejs
app.set('view engine', 'ejs');

// use res.render to load up an ejs view file

// index page
app.get('/', function(req, res) {
	res.render('public/landingpage', {moment: moment});
});

app.listen(8080);
console.log('8080 is the magic port');

memwatch.on('leak', (info) => {
  console.log(info)
});
`

**Comment by YounesTheGreat** [comment]
> I figure out that if you run your app inside a container you can limit to 256 MB the memory of the container to force the GC to clean up the unused references. In this way I fixed our situation.
> 
> I'm also using EJS forcing with the option `strict: true` to avoid possible global variable pollution.
> 
> I tried to limit the memory management on node following this [nodejs/node#7937](https://github.com/nodejs/node/issues/7937) using `--max_old_space_size=265` as V8 option but it does not seems working.
> 
> Here is how it changed the memory allocation after the limitation on container level:
> 
> <img alt="memorymanagement" width="820" src="https://user-images.githubusercontent.com/1352670/41412113-3d2ccdbc-6fdf-11e8-8a69-e3ae1c3b9875.png">

Can you tell me more about your solution i am facing the same issue

**Comment by magic890** [comment]
@YounesTheGreat that app is run inside a Docker container on Kubernetes.
Limit the memory of the Docker container to something small, like 256 MB, to force the garbage collector of NodeJS to start and free unused memory.
The `strict: true` option does not seems to make any change.

**Comment by mde** [comment]
@YounesTheGreat What we would need is a minimal example that uses only EJS, not multiple other libs including Express, and other unknown application code (e.g., public/landingpage). Your app uses EJS, and your app has a memleak. That does not mean that EJS has a memleak.
