### ISSUE TITLE
Add a work around for express users for the deprecation notice.

### ISSUE THREAD

**Issue by TimothyGu** [mde/ejs#37]

**Comment by dougwilson** [comment]
Would also be lovely if it were possible to display the message with the `depd` module, though I don't know how this module manages dependencies, since I think it needs to also work in the browser?

**Comment by dougwilson** [comment]
As for the core problem of Express users, remember, the interface to `__express` will never change. Perhaps in Express 5.0 there will be a new `__express5` interface. Until then, it may be useful to not display the message if the call came through your `__express`, since the user cannot control that call.

**Comment by TimothyGu** [comment]
> Would also be lovely if it were possible to display the message with the `depd` module

Nice self-advertising ;)

But anyway the module looks interesting. I'll look into it when I'm more awake.

> though I don't know how this module manages dependencies, since I think it needs to also work in the browser?

Yes, but it is usually @mde who handles that.

**Comment by dougwilson** [comment]
>> Would also be lovely if it were possible to display the message with the depd module

> Nice self-advertising ;)

haha. I don't like to do that, but really there is no other contenders on the deprecation message front. I thought out it because I was trying to upgrade a CLI to the newest `ejs` and I got that warning, but had no idea which of my dozens of calls to `renderFile` caused it, since there's no location data. I eventually figured it out and then ran the script again and the message was still there, apparently from yet another call.

I had to make the `depd` module to have a sane experience correcting code as a consumer of a deprecated API (since all the other deprecation modules on `npm` didn't provide it). The main thing is that module will not work in web browsers and it has no desire to, which is why I mentioned the stuff about the dependency management (if you cannot depend on non-browser deps, then clearly it's a moot point :) ).

**Comment by mde** [comment]
Also worth noting I prefer not to depend on a lot of external modules, period. It's a fine balance between providing a lot of functionality, and having a focused library that does one thing well. Erring more on the side of the latter means we don't have to package up a ton of deps when people use it in the browser.

**Comment by dougwilson** [comment]
> Erring more on the side of the latter means we don't have to package up a ton of deps when people use it in the browser.

Exactly. This is why I only brought it up, but made the note that you may not actually want to depend on it because of working in the browser :)

**Comment by TimothyGu** [comment]
Dup of #36.
