### ISSUE TITLE
Get ES6 import/export syntax working in EJS files via esm package?

### ISSUE THREAD

**Issue by chriscalo** [mde/ejs#454]
Is it possible to get ES6's import/export syntax working in EJS files via the `esm` package?

I was able to [get `require ()` working][1] in EJS files via `createRequireFromPath()` from the `module` package. Now I'm trying to get ES6's import/export syntax working, but I'm quite stuck on how to approach it.

Here's my best guess, though I'm not sure what of this is possible:
1. Transform all `<% %>` EJS tags in a file to get a plain JS string 
2. Pass that string to `esm` to transform it from ES modules to CJS modules syntax
3. Interpret that CJS output

# Why?

It's common to need helper methods inside a template file such as filters and formatters. I think it's a much cleaner syntax to just require/import such utilities from inside the EJS file instead of passing them as options when interpreting the EJS file.

One example:

``` ejs
<%
const { date, currency } = require("~/util/formatters");
%>

<!DOCTYPE html>
<div>Last updated on: <%= date(lastupdate) %></div>
<table>
  <tr>
    <td>Date</td>
    <td>Description</td>
    <td>Amount</td>
    <td>Category</td>
  </tr>
  <% for (const [i, tx] of Object.entries(transactions)) { %>
  <tr>
    <td>
      <%= date(tx.date) %>
    </td>
    <td>
      <%= tx.description %>
    </td>
    <td>
      <%= currency(tx.amount) %>
    </td>
    <td>
      <%= tx.category %>
    </td>
  </tr>
  <% } %>
</table>
```

[1]: https://github.com/chriscalo/ejs-extra/blob/master/index.js

**Comment by mde** [comment]
Isn't this just a factor of whatever runtime you're using? EJS is just executing JavaScript, which is part of its appeal. If you're rendering templates in Node, `require` et al just works OOTB — although that's pretty questionable practice. Once the modern JS runtimes sort out the competing methods of loading code via `require` vs `import`, EJS will just do the right thing. (Again, doing imports in your templates rather than passing stuff in, is pretty questionable in any case.)

**Comment by IgorArnaut** [comment]
I've also importing `moment` like this:
```EJS
<% const moment = require("moment"); %>
```
And got:
```
require is not defined
```

**Comment by mde** [comment]
I'm going to lock this conversation, since it's something people really shouldn't be doing in the first place.
