### ISSUE TITLE
Includes now throwing errors

### ISSUE THREAD

**Issue by T0MGithub** [mde/ejs#477]
After updating to the latest version of EJS, I am now getting errors while compiling my EJS templates.

The error message is: 
``SyntaxError: Unexpected token .``

I believe the lines causing these issues are ``include`` lines such as the following, as when removing such lines the errors cease.
``<% include ../partials/bootstrap/bootstrap_header.ejs %>``
``<% include ../partials/main_components/head_to_body.ejs %>``

I couldn't find any changes in the changelog which would cause this. Thanks,

**Comment by Nike1016** [comment]
- [ - ` @T0MGithub _ > ** ### ## # ** _  ` ](url)

**Comment by T0MGithub** [comment]
> * [ - `@T0MGithub _ > ** ### ## # ** _ ` ](url)

Huh? Link seems to be broken.

**Comment by mde** [comment]
It's in the current changelog: "Removed legacy preprocessor include." That usage of include is leftover from the very old v1, and was left for one major version (and for quite a long time) for backward compatibility.

We are following the semver convention of a major version bump when changing the public API. In fact, this hacky legacy feature was never actually documented in v2, but there were tests for it, so we have done a major version bump to v3. If your app depends on this feature, you can continue to install a v2.x.

Otherwise, you can convert to the modern `include` function call that is well documented, well supported, and will continue to exist in all future versions of EJS.

**Comment by T0MGithub** [comment]
Ok, sorry for the lacking research.

For anyone else with the issue, you can change the old version of include:
``<% include ../partials/bootstrap/bootstrap_header.ejs %>``
to:
``<%- include('../partials/bootstrap/bootstrap_header.ejs') %>``

**Comment by henderea** [comment]
I've been using the `include` directive in some EJS code I pre-compile into a **single** function with a gulp task, but it seems the `include(...)` function doesn't work the same.  Is that something that will start working once the gulp task packages support EJS 3.x, or is there something else I would need to do to get those other files embedded into the overall function?

**Comment by simllll** [comment]
the major difference is that include 'file.ejs' has passed all parameters as a side effect, but include('file.ejs') does not. Any idea how I can pass the whole data context to the include method to get an easy transition?

**Comment by henderea** [comment]
Well, what I meant is that my gulp task gives me an output that has the `include('parts/part1.ejs')` method call instead of the content of the file.  I'm pre-compiling the templates for use in the browser, so I can't have it pulling in other files like that.  Maybe I'm just using the wrong gulp task implementation?  This is the compiling part of my gulp task:

```javascript
.pipe(through2.obj(function(file, enc, next) {
    try {
        var contents = file.contents.toString();
        var compiledFunction = ejs.compile(contents, {
            filename: file.path,
            client: true
        }).toString();
        file.contents = new Buffer(compiledFunction);
        file.path = replaceExt(file.path, '.js');
    } catch(err) {
        this.emit('error', new PluginError('gulp-ejs-precompiler', err));
    }
    next(null, file);
}))
```

It works with v2.x and the preprocessor directive, but not with v3.x and the function call.  `ejs` is just `require('ejs')`

**Comment by mde** [comment]
@simllll By default, the local variables live in an object called `locals` — for when people are opting out of the use of `with` for execution. (The name of this object is also configurable.)

```javascript
> let ejs = require('ejs');
undefined
> ejs.render('<%- JSON.stringify(locals); %>', {foo: 'FOO', bar: 'BAR'});
'{"foo":"FOO","bar":"BAR"}'
``

**Comment by simllll** [comment]
Thanks, this helps already a lot to merge the object with temporary data. But is there also something that referes to the current scope variables? E.g.
ejs.render('<% var keep='blub'; var something = 'this is very old code btw'; %> <% /* access to keep and something? Or some was to see what is available in the current context */ %>', {...});
``

**Comment by henderea** [comment]
@mde: is there any way with ejs 3+ to precompile `include`-using templates in a build process for use in the browser?  I have a gulp task (listed in an earlier comment) that compiles a set of templates into a single JS file for loading into the browser and using in client-side JS to insert into the DOM with jQuery.  The raw EJS templates aren't accessible to the browser in any way, but the `include(...)` function is left untouched (and thus non-functional) in the `ejs.compile` output.  Right now, I am unable to upgrade to EJS 3.x because it doesn't support the `include` preprocessor directive that actually _works_ in my use case.

Is there no way to separate the compiled templates from the raw EJS files when using `include(...)`?

**Comment by ExE-Boss** [comment]
You&nbsp;can&nbsp;provide a&nbsp;custom `include(…)`&nbsp;function as&nbsp;the&nbsp;third&nbsp;parameter at&nbsp;runtime by&nbsp;compiling in&nbsp;`client`&nbsp;mode.

This&nbsp;is the&nbsp;default&nbsp;behaviour: https://github.com/mde/ejs/blob/d8ae91d97e74e100d58a4c53835682ce5a255f08/lib/ejs.js#L647-L656
