### ISSUE TITLE
Need to define '' or null for each key used?

### ISSUE THREAD

**Issue by mengdu** [mde/ejs#482]
```
> ejs.render('<%= msg %>', {})
Thrown:
{ ReferenceError: ejs:1
 >> 1| <%= msg %>

msg is not defined
```

I have to use `ejs.render('<%= msg %>', { msg: '' })` ?

**Comment by ExE-Boss** [comment]
That’s&nbsp;because EJS&nbsp;uses the&nbsp;`with`&nbsp;statement.

If&nbsp;you&nbsp;know which&nbsp;properties you&nbsp;want to&nbsp;always be&nbsp;available, you&nbsp;can&nbsp;use the&nbsp;`destructuredLocals` option, which&nbsp;takes an&nbsp;array of&nbsp;JavaScript&nbsp;identifiers.

**Comment by mde** [comment]
More specifically, this is just how JavaScript works. (We use `with` to create a scope with local variables defined from the outside.) If you reference an undeclared variable in JavaScript, you get a ReferenceError:

```bash
mdes-mbp:~ mde$ node
Welcome to Node.js v12.6.0.
Type ".help" for more information.
> msg;
Thrown:
ReferenceError: msg is not defined
```
EJS is just JavaScript.

Another alternative to @ExE-Boss's suggestion would be directly accessing the `locals` object which is also available inside the template scope:

```javascript
> ejs.render('<%= locals.msg %>', {});
> ''
```
This is because referencing a value for an undefined key in a JS object just returns `undefined`. The one semi-magical thing EJS does do for you outside vanilla JS execution is coerce `undefined` and `null` to empty string, which is almost always the desired behavior in a template. (Nobody wants the literal strings 'undefined' and 'null' in their templates.

You can also change the name of the `locals` object using the `localsName` option.
