### ISSUE TITLE
Please make pass 'Cannot read property ~ of undefined'

### ISSUE THREAD

**Issue by dancinlife** [mde/ejs#514]
Please make pass 'Cannot read property ~ of undefined'
Please make 'Softness(flexibility) value output'

**example use**
<%~ email %>

**example output**
**1. if email exists**
ooo@ooo.com

**2. if email doesn't exist (undefined or null)**
(empty string)

**Current method (Too many logic in view)**
```
<% if (typeof (flash) !== 'undefined' && typeof (flash) !== 'null' && typeof (flash.data) !== 'undefined' && typeof (flash.data) !== 'null' ) { %>
<input type="text" name="email" placeholder="Email" value="<% if (flash.data.email !== 'null') { %><%= flash.data.email %><% } %>">
<input type="password" name="password" placeholder="Password" value="<% if (flash.data.password !== 'null') { %><%= flash.data.password %><% } %>">
<input type="password" name="passwordCheck" placeholder="Password Check" value="<% if (flash.data.passwordCheck !== 'null') { %><%= flash.data.passwordCheck %><% } %>">
<input type="name" name="name" placeholder="Name" value="<% if (flash.data.name !== 'null') { %><%= flash.data.name %><% } %>">
<button>Join</button>
<% } else { %>
<input type="text" name="email" placeholder="Email">
<input type="password" name="password" placeholder="Password">
<input type="password" name="password_check" placeholder="Password Check">
<input type="name" name="name" placeholder="Name">
<button>Join</button>
<% } %>
```

**Softness method**
```
<input type="text" name="email" placeholder="Email" value="<%~ flash.data.email %>">
<input type="password" name="password" placeholder="Password" value="<%~ flash.data.password %>">
<input type="password" name="passwordCheck" placeholder="Password Check" value="<%~ flash.data.passwordCheck %>">
<input type="name" name="name" placeholder="Name" value="<%~ flash.data.name %>">
<button>Join</button>
```

**Comment by mde** [comment]
I take your point, but usually all these tests are done outside the template, and you pass known-good data. I'll take a look at how easy it might be to implement something for this.

**Comment by dancinlife** [comment]
Thanks for reading my comment.
But now i don't know, this is a good way.
Because I am a beginner programmer who is 1year old.
Please just think lightly this. Thank you :)

**Comment by mde** [comment]
It occurs to me that we already handle some level of what you're describing (output that is either `null` or `undefined`), but we cannot and should not be testing to see if all (global-ish) variables you attempt to reference in a template have been declared or not.

This is just a problem of using the default EJS settings where your passed variables turn into (effectively) global variables using JavaScript's `with` functionality. All those variables then are references in your template directly (like your `flash` variable above).

A workaround for what you're doing here might be to use an explicit "locals" object, instead of these implicit global-ish variables. Then, when you reference them as keys on the locals object, JavaScript will return `undefined` for ones it does not find, instead of throwing an error. EJS will render nothing when the output of a particular tag is `null` or `undefined`.

The default name for the "locals" object is `locals`, but you can give it a custom name if you want. Consider the following:

```javascript
// Throws error because `foo` is not defined
ejs.render('<%= foo; %>', {});
// Renders nothing
ejs.render('<%= __.foo; %>', {}, {_with: false, localsName: '__'});
```
This approach might be good for what you're trying to do.

**Comment by dancinlife** [comment]
Thank you for your help.
I will try this !!!
