### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Umut-Ozkan** [mde/ejs#599]
Hello!
I have a question
Does it support setInterval on EJS?

I have Shard Statistics on my website. I use await. But however, it shows the same ping number after 5 seconds, but it shows the same when it should show different.

Is there a recurring feature on EJS?

Translated By Google Translate

**Comment by Umut-Ozkan** [comment]
@mde help me

**Comment by mde** [comment]
I don't understand your question. This sounds like a problem with your application code, not the EJS library. Your best bet is to write some wrapping code that will periodically invoke the `render` call. Since this is not a problem with EJS, I am going to close this issue. Please feel free to reopen, or open a new one if there is a problem with EJS itself.
