### ISSUE TITLE
Access localStorage/sessionStorage

### ISSUE THREAD

**Issue by AndresSalomon1990** [mde/ejs#608]
Hi, is there a way to access the localStorage or sessionStorage inside an ejs file? I'm trying but I'm getting an error. That's because it is rendering in the server? Thanks!

**Comment by mde** [comment]
EJS files should be for rendering templates and nothing else. If you're wanting to do I/O, like accessing a DB in server code, or accessing localStorage in browser code, you should do it outside of your template file. Since this issue has nothing to do with EJS itself, I am going to close it. If you have an issue with the EJS library itself, please feel free to open a new issue.

**Comment by AndresSalomon1990** [comment]
Thank you @mde !! Sorry for posting it here.
