### ISSUE TITLE
Images are not rendered using Ejs parameters.

### ISSUE THREAD

**Issue by victordsantoss** [mde/ejs#686]
Hi, 

When passing dynamic parameters to images, they are not rendered using the ejs library. This error only occurs on Debian 10 build.

here is my code: 

`     

      <div>
            <img src="<%- event_cover %>"/>
        </div>

`

**Comment by mde** [comment]
If basic rendering were broken, we would have broken tests, and hundreds of thousands of complaints. (EJS is installed via NPM around 10 million times a week.)

Your problem is almost certainly in your application code, or something specific to your Debian environment, like your JavaScript runtime. I'm happy to take a look at this if you can provide a minimal failing test that demonstrates it's actually a problem with the EJS library itself. Please feel free to reopen this issue if you create such a test.
