### ISSUE TITLE
New async renderFile causes subtle bugs in other libraries

### ISSUE THREAD

**Issue by CherryDT** [mde/ejs#70]
The change introduced in https://github.com/mde/ejs/issues/53 causes havoc with all libraries which monitor whether res.end was called (by proxying it).

For example, express-session monitors res.end calls in order to commit the session.

Also, CompoundJS will only continue routing if a controller called res.end.

The latter caused a problem in my applications, because I had several routes and a "catch-all" route for 404 errors at the end. What happened now was that for every request, the correct controller rendered its view by calling "renderFile" and then "next", but then, because renderFile is now async, CompoundJS didn't detect a res.end call and resumes routing. It now triggers my 404 route. The 404 route also renders a view. Then the first view is actually sent, then the second one - now crashing with "headers already sent".

**Comment by mde** [comment]
I was actually thinking of this while reading this post on async APIs: http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony I was kind of surprised to see fs.readFileSync used in the original code for getting template text when there was already a callback-based API in place for renderFile. I guess the assumption was that if EJS rendering was in a perf-sensitive area then caching would be in anyhow, and the sync calls to the filesystem wouldn't matter.

I'm not super religious about Node/async, and I have to admit that the experience making template-rendering in Geddy totally async resulted in some pretty awful bug reports (https://github.com/geddy/geddy/issues/349). But it also seems kind of weird that a call that clearly gets a filepath, and takes a callback is expected to be synchronous. If it's suppose to be sync then why not just return the rendered content the way `render` does? (Well obviously to plug into Express's async API.) So the end result is having to make the API take a callback, but having to make the callback execute synchronously so people listening for the response to end can assume all the rendering work is done by then. Seems kind of bad all around.

Do these problems happen anywhere by using `renderFile` directly? Or are the all via using EJS inside of Express rendering?

**Comment by TimothyGu** [comment]
First, I have no problem with reverting the aforementioned commit. After reading Isaac's blog post I feel that make the function fully synchronous like the function really is, is the best solution under the circumstances. This is technically an API break, but I guess the commit that made the function pseudo-async broke the API as well, so what the heck.

For the matter of reading files, according to @ForbesLindesay in jstransformers/jstransformer#2, it is rarely the performance bottleneck anyway, so I guess this is fine for now.

The way Jade handles it might be interesting. All of its functions provide an optional `callback` parameter that gets called synchronously, and return the result if no callbacks are provided.

Second, I believe it is wrong when third-party frameworks make assumptions on the (a)synchronicity of the templating engines. There are quite a few templating engines out there that are asynchronous, for instance [qejs](https://github.com/jepso/QEJS). If all Express.js-compliant templating engines are synchronous, they would have just made `__express` return a result instead of passing a callback to it.

**Comment by mde** [comment]
All right, this is fixed in 32792dccfb0f5eac2efabb9fab7085735ba500ad by reverting the change. (Couldn't get a clean `git revert`, so it was a manual revert.) Longer term I like the idea of making the callback optional, but at least this gets people unstuck. This fix was pushed to NPM in v2.3.1.

**Comment by dougwilson** [comment]
Just as a note, this absolutely does not cause any problems with express-session (assuming you are using at least some relatively recent version), so I'm not sure why it was dragged under the bus here, so to say...
