### ISSUE TITLE
ETS

### ISSUE THREAD

**Issue by AngeloCore** [mde/ejs#715]
EJS but with typescript support?

**Comment by mde** [comment]
The "JS" in EJS is for "JavaScript." The main benefit of EJS is that it is simply JavaScript. That's the entire point.

**Comment by AngeloCore** [comment]
I mean add support for types when embedding

**Comment by mde** [comment]
I understand what you meant. It's not something I intend to pursue for EJS.

**Comment by nhusby** [comment]
This would be very helpful.  We are going all in on TypeScript and it's preventing a lot of bugs.  We still run into issues with templates crashing and preventing emails going out because a junior dev came along and changed the input data somewhere upstream not realizing it impacts data required by a template because there is no visibility into its requirements without scanning through the whole thing.

Actually using typing is optional, which makes TypeScript really easy to adopt... it's just JavaScript, but I get that you're not interested... it's probably something that should be a fork anyway.  

@mde any advice for forking?

**Comment by AngeloCore** [comment]
Also a proper vscode extension wouldn't be bad 😅

**Comment by mde** [comment]
Nothing to prevent your using EJS in your own TS code. As you say, it's a superset of JavaScript. I know exactly what TypeScript is, and how it works. I have used it. And as I have already said numerous times, I don't find it to be a good tradeoff in terms of return on investment. I have zero plans for adopting it for EJS.
