### ISSUE TITLE
Option to suppress leading spaces for control flow?

### ISSUE THREAD

**Issue by mwise** [mde/ejs#87]
I'm having some difficulty getting the output I expect when using control flow statements that are indented. When the control flow statement starts at column 0, all is well (the first case in my example code below). However, when the control flow statement is indented, the inner statements are seem to inherit the indentation of the control flow plus their own indentation position. 

Given the following input.ejs:
```
<ul>
<% ['1', '2', '3'].forEach(function(num) { -%>
  <li><%= num %></li>
<% }) -%>
</ul>


  <ul>
  <% ['1', '2', '3'].forEach(function(num) { -%>
    <li><%= num %></li>
  <% }) -%>
  </ul>


  <ul>
  <% ['1', '2', '3'].forEach(function(num) { -%>
    <li><%= num %></li>
  <% }) %>
  </ul>
```

I'm seeing the following output:
```
<ul>
  <li>1</li>
  <li>2</li>
  <li>3</li>
</ul>


  <ul>
      <li>1</li>
      <li>2</li>
      <li>3</li>
    </ul>


  <ul>
      <li>1</li>
      <li>2</li>
      <li>3</li>
  
  </ul>
```

My use case is a code generation utility that uses EJS to generate html/js files. It's a bit awkward to have to have all of my control-flow statements begin at column 0. It would be great if lines that were exclusively control flow were ignored outright and the statements within them were evaluated with their "absolute" indentation, not within the indentation of the control flow. The issue is illustrated in the above example, but in my actual use case, I'm trying to use includes the same way and seeing the same behavior. 

Is there some usage that I'm missing that would help here? It would seem that if we could omit both the trailing and leading whitespace as well as the newline for `<% control_flow `%>` lines, then this would just work. I imagine includes would take a bit more doing - as it is now, we're using an awkward "pass a padding string to a recursive function that generates output and manages indentation" approach to rendering complex elements within a control flow statement.

Any help would be greatly appreciated!

**Comment by mde** [comment]
This is a long-standing problem with any type of compilation -- are you optimizing for the source, or for the generated output? I'm going to say fixing this problem is a bit outside the purview of plain EJS, since a person's expectations of how they should write their code, and what should be output, could vary widely. If you really care about the indentation of your generated output, your best bet is probably to use something like JS Beautify's HTML formatter: https://github.com/beautify-web/js-beautify#css--html. (It's available as an NPM module: https://www.npmjs.com/package/js-beautify)
